version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/api/services/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Required - User must provide in root .env
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Container-specific paths and config
      - INTERPRETER_TYPE=r
      - R_PATH=/usr/bin/R
      - WORKING_DIRECTORY=/workspace
      - ALLOWED_HOSTS=localhost:3000,frontend:3000
      - FRONTEND_URL=localhost:3000
      - ENABLE_CORS=TRUE
      - INTERPRETER_TIMEOUT=120
    volumes:
      - workspace:/workspace
    stdin_open: true
    tty: true
    networks:
      - rpilot-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVICES_URL=http://backend:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - rpilot-net

volumes:
  workspace:

networks:
  rpilot-net:
    driver: bridge
