version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/api/services/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - INTERPRETER_TYPE=r
      - R_PATH=/usr/bin/R
      - WORKING_DIRECTORY=/workspace
      # Allow both direct access and access through frontend hostname
      - ALLOWED_HOSTS=localhost:3000,frontend:3000
      - FRONTEND_URL=localhost:3000
      - ENABLE_CORS=TRUE
    volumes:
      - workspace:/workspace
    stdin_open: true
    tty: true
    networks:
      - rpilot-net

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Use container name for direct communication
      - NEXT_PUBLIC_SERVICES_URL=http://backend:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - rpilot-net

volumes:
  workspace:

networks:
  rpilot-net:
    driver: bridge
